using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class FinalGame_ladderItem : MonoBehaviour
{
    //public Sprite brokenBox;
    //public bool broken;
    public AudioSource audio;
    public bool ladder;
    // Start is called before the first frame update
    void Start()
    {
        //broken=false;
        audio = GetComponent<AudioSource>();
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        //transform.Rotate(0.5f*Vector3.right);
        //transform.Rotate(0.5f * Vector3.up);
        //if(broken)
        //gameObject.GetComponent<SpriteRenderer>().sprite = brokenBox;

    }
}
